# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0649824674b78094fc4981e15d6badf5e52d32cf84468e9e07d1858b14793830b36ea2dd8bdfea52c7b6c4b49202a15692b303d3216c670650c382cf49ba6d44

test:
  secret_key_base: 15f33e5a39ce3796b0671890ba091fd044250a45fb72e21a39bc822e25bf023b54badbf230ca03f143cc24ca8e1dbd8b11f447be60e24316ab7e04269a6ad44e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
